- name: Dependencies are installed
  apt:
    name:
      - debconf
      - lsb-base
      - perl
      - libio-socket-ssl-perl
      - libdata-validate-ip-perl

- block:
    - name: Download and unpack ddclient release archive
      unarchive:
        src: "https://github.com/ddclient/ddclient/archive/refs/tags/v{{ ddclient_version }}.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Install ddclient binary
      command: "cp /tmp/ddclient-{{ ddclient_version }}/ddclient {{ ddclient_executable_path }}"
  always:
    - name: remove ddclient installer files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/ddclient.tar.gz
        - "/tmp/ddclient-{{ ddclient_version }}"
